### ISSUE TITLE
Gurobi failure when using dynamics with influence zone

### ISSUE THREAD

**Issue by rtkg** [neckutrek/hiqp#18]
Gurobi does not seem to be able to handle the std::numeric_limits<double>::infinity() bound to which e_dot_star_ is set when e_ is outside the influence zone. It fails with status code 12 ('Optimization was terminated due to unrecoverable numerical difficulties') in such situations.

**Comment by rtkg** [comment]
How about removing the influence zone from the first order dynamics and the min-jerk and, instead, implement a separate non-linear dynamics as de*=-k*sinh(e). The hyperbolic sine exhibits the behaviour we'd like as, by means of tuning a single parameter k, it can be made very large with a sharp increase while still being continuous and stable. Such dynamics might even be useful for equality tasks. Also, this might be a nice candidate to replace the current first order behaviour for the joint limit avoidance task.

**Comment by neckutrek** [comment]
Sounds good.

**Comment by rtkg** [comment]
Also -K*e^3 might be an interesting candidate. It has an inflection point at e=0 which might be useful for slow convergence

**Comment by rtkg** [comment]
Added a 1st order cubic dynamics as above on feature-collision-avoidance:	
        hiqp_core/include/hiqp/tasks/dynamics_first_order_cubic.h
	hiqp_core/src/tasks/dynamics_first_order_cubic.cpp

**Comment by neckutrek** [comment]
Hmm. since d/de de* = 0 when e=0 the task would never converge right? the same applies for sinh? sinh makes sense though as there's a cutoff, something that de*=-ke does not have.
In what applications would -ke^3 be applicable when -ke isn't?

**Comment by neckutrek** [comment]
I'll add sinh and remove influence zone from -ke on devel.

**Comment by neckutrek** [comment]
It does make sense in practice I saw. I'll merge this into devel.

**Comment by neckutrek** [comment]
Actually, -ke^3 is not a first order dynamics, but a third order dynamics without first and second order terms, right? So one could think of de*=-ae^3-be^2-ce. However:
- adding a second order term would shift the dynamics along the e-axis, it wouldn't make sense to not mirror the dynamics on the de*-axis as the behaviour then would differ between positive and negative e. So one would always want b=0.
- letting c<0 would yield the profile "- 0 + 0 -" of the curve, i.e. there would be a local minima on the left side of origo, and a local maxima on the right side. this is not desirable either, since when approaching e=0 the behaviour would suddenyl change into the opposite direction.
- letting c>0 would simply blend the cubic curve to look more like -ke. this could be desirable.

So as I see it, either a cubic dynamics -ke^3 is added (i.e. refactor TDynFirstOrderCubic -> TDynCubic), or TDynFirstOrder -> TDynThirdOrder with parameters for setting two positive values as parameters forming de*=-ae^3-be for positive constants a,b.
Since the linearity in first-order dynamics is often desired, I think the first option is best.

Keep TDynFirstOrder and refactor the name of TDynFirstOrderCubic -> TDynCubic?

**Comment by rtkg** [comment]
Mmm,  the order in dynamical systems refers to the order of the highest derivative. It would probably be more accurate to call the current first order dynamics 'linear first order'. Also, e.g., de*=-sinh(k*e) is a (nonlinear) first order system.

Indeed, you could come up with a general polynomial describing your system. However, I guess symmetry is, as you said one desired property. 

Basically, I'd agree with your suggestion of the first option. Regarding naming - I leave it up to you. Additional options could also be TDynFirstOrder -> TDynFirstOrderLinear and keep TDynFirstOrderCubic or  TDynFirstOrder -> TDynLinear and TDynFirstOrderCubic -> TDynCubic assuming that we only deal with first order systems anyway.

**Comment by neckutrek** [comment]
I see, ok. Thanks.


---
Med vänlig hälsning / Best regards,
  Marcus A Johansson
  +46 (0)70 315 73 77

2016-12-14 11:53 GMT+01:00 Robert Krug <notifications@github.com>:

**Comment by neckutrek** [comment]
Naming of task dynamics and definitions has been updated.
TDynLinear, TDynCubic and TDynHyperSin are now available and are tested once.

Close issue?
